// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.Empresa;
import javax.persistence.Entity;

privileged aspect Empresa_Roo_Jpa_Entity {
    
    declare @type: Empresa: @Entity;
    
}
