// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.Formacion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Formacion_Roo_Configurable {
    
    declare @type: Formacion: @Configurable;
    
}
