// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.Comunidad;
import iw2016_ett.domain.ComunidadDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ComunidadDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ComunidadDataOnDemand: @Component;
    
    private Random ComunidadDataOnDemand.rnd = new SecureRandom();
    
    private List<Comunidad> ComunidadDataOnDemand.data;
    
    public Comunidad ComunidadDataOnDemand.getNewTransientComunidad(int index) {
        Comunidad obj = new Comunidad();
        return obj;
    }
    
    public Comunidad ComunidadDataOnDemand.getSpecificComunidad(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Comunidad obj = data.get(index);
        Long id = obj.getId();
        return Comunidad.findComunidad(id);
    }
    
    public Comunidad ComunidadDataOnDemand.getRandomComunidad() {
        init();
        Comunidad obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Comunidad.findComunidad(id);
    }
    
    public boolean ComunidadDataOnDemand.modifyComunidad(Comunidad obj) {
        return false;
    }
    
    public void ComunidadDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Comunidad.findComunidadEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Comunidad' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Comunidad>();
        for (int i = 0; i < 10; i++) {
            Comunidad obj = getNewTransientComunidad(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
