// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.DemandanteDataOnDemand;
import iw2016_ett.domain.ExperienciaLaboral;
import iw2016_ett.domain.ExperienciaLaboralDataOnDemand;
import iw2016_ett.domain.PuestoTrabajoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExperienciaLaboralDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExperienciaLaboralDataOnDemand: @Component;
    
    private Random ExperienciaLaboralDataOnDemand.rnd = new SecureRandom();
    
    private List<ExperienciaLaboral> ExperienciaLaboralDataOnDemand.data;
    
    @Autowired
    DemandanteDataOnDemand ExperienciaLaboralDataOnDemand.demandanteDataOnDemand;
    
    @Autowired
    PuestoTrabajoDataOnDemand ExperienciaLaboralDataOnDemand.puestoTrabajoDataOnDemand;
    
    public ExperienciaLaboral ExperienciaLaboralDataOnDemand.getNewTransientExperienciaLaboral(int index) {
        ExperienciaLaboral obj = new ExperienciaLaboral();
        setEmpresa(obj, index);
        setFechaFin(obj, index);
        setFechaInicio(obj, index);
        return obj;
    }
    
    public void ExperienciaLaboralDataOnDemand.setEmpresa(ExperienciaLaboral obj, int index) {
        String Empresa = "Empresa_" + index;
        obj.setEmpresa(Empresa);
    }
    
    public void ExperienciaLaboralDataOnDemand.setFechaFin(ExperienciaLaboral obj, int index) {
        Date FechaFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaFin(FechaFin);
    }
    
    public void ExperienciaLaboralDataOnDemand.setFechaInicio(ExperienciaLaboral obj, int index) {
        Date FechaInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaInicio(FechaInicio);
    }
    
    public ExperienciaLaboral ExperienciaLaboralDataOnDemand.getSpecificExperienciaLaboral(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ExperienciaLaboral obj = data.get(index);
        Long id = obj.getId();
        return ExperienciaLaboral.findExperienciaLaboral(id);
    }
    
    public ExperienciaLaboral ExperienciaLaboralDataOnDemand.getRandomExperienciaLaboral() {
        init();
        ExperienciaLaboral obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ExperienciaLaboral.findExperienciaLaboral(id);
    }
    
    public boolean ExperienciaLaboralDataOnDemand.modifyExperienciaLaboral(ExperienciaLaboral obj) {
        return false;
    }
    
    public void ExperienciaLaboralDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ExperienciaLaboral.findExperienciaLaboralEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ExperienciaLaboral' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ExperienciaLaboral>();
        for (int i = 0; i < 10; i++) {
            ExperienciaLaboral obj = getNewTransientExperienciaLaboral(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
