// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.DemandanteDataOnDemand;
import iw2016_ett.domain.Formacion;
import iw2016_ett.domain.FormacionDataOnDemand;
import iw2016_ett.domain.TipoFormacion;
import iw2016_ett.domain.TitulacionesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FormacionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FormacionDataOnDemand: @Component;
    
    private Random FormacionDataOnDemand.rnd = new SecureRandom();
    
    private List<Formacion> FormacionDataOnDemand.data;
    
    @Autowired
    DemandanteDataOnDemand FormacionDataOnDemand.demandanteDataOnDemand;
    
    @Autowired
    TitulacionesDataOnDemand FormacionDataOnDemand.titulacionesDataOnDemand;
    
    public Formacion FormacionDataOnDemand.getNewTransientFormacion(int index) {
        Formacion obj = new Formacion();
        setFechaFin(obj, index);
        setFechaInicio(obj, index);
        setObservaciones(obj, index);
        setTipoFormacion(obj, index);
        setTitulo(obj, index);
        return obj;
    }
    
    public void FormacionDataOnDemand.setFechaFin(Formacion obj, int index) {
        Date FechaFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaFin(FechaFin);
    }
    
    public void FormacionDataOnDemand.setFechaInicio(Formacion obj, int index) {
        Date FechaInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaInicio(FechaInicio);
    }
    
    public void FormacionDataOnDemand.setObservaciones(Formacion obj, int index) {
        String Observaciones = "Observaciones_" + index;
        obj.setObservaciones(Observaciones);
    }
    
    public void FormacionDataOnDemand.setTipoFormacion(Formacion obj, int index) {
        TipoFormacion tipoFormacion = TipoFormacion.class.getEnumConstants()[0];
        obj.setTipoFormacion(tipoFormacion);
    }
    
    public void FormacionDataOnDemand.setTitulo(Formacion obj, int index) {
        String Titulo = "Titulo_" + index;
        obj.setTitulo(Titulo);
    }
    
    public Formacion FormacionDataOnDemand.getSpecificFormacion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Formacion obj = data.get(index);
        Long id = obj.getId();
        return Formacion.findFormacion(id);
    }
    
    public Formacion FormacionDataOnDemand.getRandomFormacion() {
        init();
        Formacion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Formacion.findFormacion(id);
    }
    
    public boolean FormacionDataOnDemand.modifyFormacion(Formacion obj) {
        return false;
    }
    
    public void FormacionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Formacion.findFormacionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Formacion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Formacion>();
        for (int i = 0; i < 10; i++) {
            Formacion obj = getNewTransientFormacion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
