// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.Contrato;
import iw2016_ett.domain.Estado;
import iw2016_ett.domain.LocalizacionDataOnDemand;
import iw2016_ett.domain.Oferta;
import iw2016_ett.domain.OfertaDataOnDemand;
import iw2016_ett.domain.Perfil;
import iw2016_ett.domain.PuestoTrabajoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OfertaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OfertaDataOnDemand: @Component;
    
    private Random OfertaDataOnDemand.rnd = new SecureRandom();
    
    private List<Oferta> OfertaDataOnDemand.data;
    
    @Autowired
    LocalizacionDataOnDemand OfertaDataOnDemand.localizacionDataOnDemand;
    
    @Autowired
    PuestoTrabajoDataOnDemand OfertaDataOnDemand.puestoTrabajoDataOnDemand;
    
    public Oferta OfertaDataOnDemand.getNewTransientOferta(int index) {
        Oferta obj = new Oferta();
        setContrato(obj, index);
        setEstado(obj, index);
        setFechaFin(obj, index);
        setFechaInicio(obj, index);
        setNumeroVacantes(obj, index);
        setPerfil(obj, index);
        setSueldo(obj, index);
        setTipoContrato(obj, index);
        setTitulo(obj, index);
        return obj;
    }
    
    public void OfertaDataOnDemand.setContrato(Oferta obj, int index) {
        Contrato Contrato = Contrato.class.getEnumConstants()[0];
        obj.setContrato(Contrato);
    }
    
    public void OfertaDataOnDemand.setEstado(Oferta obj, int index) {
        Estado Estado = Estado.class.getEnumConstants()[0];
        obj.setEstado(Estado);
    }
    
    public void OfertaDataOnDemand.setFechaFin(Oferta obj, int index) {
        Date FechaFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaFin(FechaFin);
    }
    
    public void OfertaDataOnDemand.setFechaInicio(Oferta obj, int index) {
        Date FechaInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaInicio(FechaInicio);
    }
    
    public void OfertaDataOnDemand.setNumeroVacantes(Oferta obj, int index) {
        int NumeroVacantes = index;
        obj.setNumeroVacantes(NumeroVacantes);
    }
    
    public void OfertaDataOnDemand.setPerfil(Oferta obj, int index) {
        Perfil Perfil = Perfil.class.getEnumConstants()[0];
        obj.setPerfil(Perfil);
    }
    
    public void OfertaDataOnDemand.setSueldo(Oferta obj, int index) {
        float Sueldo = new Integer(index).floatValue();
        obj.setSueldo(Sueldo);
    }
    
    public void OfertaDataOnDemand.setTipoContrato(Oferta obj, int index) {
        String TipoContrato = "TipoContrato_" + index;
        obj.setTipoContrato(TipoContrato);
    }
    
    public void OfertaDataOnDemand.setTitulo(Oferta obj, int index) {
        String titulo = "titulo_" + index;
        obj.setTitulo(titulo);
    }
    
    public Oferta OfertaDataOnDemand.getSpecificOferta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Oferta obj = data.get(index);
        Long id = obj.getId();
        return Oferta.findOferta(id);
    }
    
    public Oferta OfertaDataOnDemand.getRandomOferta() {
        init();
        Oferta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Oferta.findOferta(id);
    }
    
    public boolean OfertaDataOnDemand.modifyOferta(Oferta obj) {
        return false;
    }
    
    public void OfertaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Oferta.findOfertaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Oferta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Oferta>();
        for (int i = 0; i < 10; i++) {
            Oferta obj = getNewTransientOferta(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
