// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.DemandanteDataOnDemand;
import iw2016_ett.domain.PuestoTrabajo;
import iw2016_ett.domain.PuestoTrabajoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PuestoTrabajoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PuestoTrabajoDataOnDemand: @Component;
    
    private Random PuestoTrabajoDataOnDemand.rnd = new SecureRandom();
    
    private List<PuestoTrabajo> PuestoTrabajoDataOnDemand.data;
    
    @Autowired
    DemandanteDataOnDemand PuestoTrabajoDataOnDemand.demandanteDataOnDemand;
    
    public PuestoTrabajo PuestoTrabajoDataOnDemand.getNewTransientPuestoTrabajo(int index) {
        PuestoTrabajo obj = new PuestoTrabajo();
        setNombre(obj, index);
        return obj;
    }
    
    public void PuestoTrabajoDataOnDemand.setNombre(PuestoTrabajo obj, int index) {
        String Nombre = "Nombre_" + index;
        obj.setNombre(Nombre);
    }
    
    public PuestoTrabajo PuestoTrabajoDataOnDemand.getSpecificPuestoTrabajo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PuestoTrabajo obj = data.get(index);
        Long id = obj.getId();
        return PuestoTrabajo.findPuestoTrabajo(id);
    }
    
    public PuestoTrabajo PuestoTrabajoDataOnDemand.getRandomPuestoTrabajo() {
        init();
        PuestoTrabajo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PuestoTrabajo.findPuestoTrabajo(id);
    }
    
    public boolean PuestoTrabajoDataOnDemand.modifyPuestoTrabajo(PuestoTrabajo obj) {
        return false;
    }
    
    public void PuestoTrabajoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PuestoTrabajo.findPuestoTrabajoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PuestoTrabajo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PuestoTrabajo>();
        for (int i = 0; i < 10; i++) {
            PuestoTrabajo obj = getNewTransientPuestoTrabajo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
