// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.PuestoTrabajo;
import iw2016_ett.domain.PuestoTrabajoDataOnDemand;
import iw2016_ett.domain.PuestoTrabajoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PuestoTrabajoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PuestoTrabajoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PuestoTrabajoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PuestoTrabajoIntegrationTest: @Transactional;
    
    @Autowired
    PuestoTrabajoDataOnDemand PuestoTrabajoIntegrationTest.dod;
    
    @Test
    public void PuestoTrabajoIntegrationTest.testCountPuestoTrabajoes() {
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", dod.getRandomPuestoTrabajo());
        long count = PuestoTrabajo.countPuestoTrabajoes();
        Assert.assertTrue("Counter for 'PuestoTrabajo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testFindPuestoTrabajo() {
        PuestoTrabajo obj = dod.getRandomPuestoTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to provide an identifier", id);
        obj = PuestoTrabajo.findPuestoTrabajo(id);
        Assert.assertNotNull("Find method for 'PuestoTrabajo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PuestoTrabajo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testFindAllPuestoTrabajoes() {
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", dod.getRandomPuestoTrabajo());
        long count = PuestoTrabajo.countPuestoTrabajoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PuestoTrabajo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PuestoTrabajo> result = PuestoTrabajo.findAllPuestoTrabajoes();
        Assert.assertNotNull("Find all method for 'PuestoTrabajo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PuestoTrabajo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testFindPuestoTrabajoEntries() {
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", dod.getRandomPuestoTrabajo());
        long count = PuestoTrabajo.countPuestoTrabajoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PuestoTrabajo> result = PuestoTrabajo.findPuestoTrabajoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PuestoTrabajo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PuestoTrabajo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testFlush() {
        PuestoTrabajo obj = dod.getRandomPuestoTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to provide an identifier", id);
        obj = PuestoTrabajo.findPuestoTrabajo(id);
        Assert.assertNotNull("Find method for 'PuestoTrabajo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPuestoTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PuestoTrabajo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testMergeUpdate() {
        PuestoTrabajo obj = dod.getRandomPuestoTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to provide an identifier", id);
        obj = PuestoTrabajo.findPuestoTrabajo(id);
        boolean modified =  dod.modifyPuestoTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        PuestoTrabajo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PuestoTrabajo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", dod.getRandomPuestoTrabajo());
        PuestoTrabajo obj = dod.getNewTransientPuestoTrabajo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PuestoTrabajo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PuestoTrabajo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PuestoTrabajoIntegrationTest.testRemove() {
        PuestoTrabajo obj = dod.getRandomPuestoTrabajo();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PuestoTrabajo' failed to provide an identifier", id);
        obj = PuestoTrabajo.findPuestoTrabajo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PuestoTrabajo' with identifier '" + id + "'", PuestoTrabajo.findPuestoTrabajo(id));
    }
    
}
