// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.OfertaDataOnDemand;
import iw2016_ett.domain.Titulaciones;
import iw2016_ett.domain.TitulacionesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TitulacionesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TitulacionesDataOnDemand: @Component;
    
    private Random TitulacionesDataOnDemand.rnd = new SecureRandom();
    
    private List<Titulaciones> TitulacionesDataOnDemand.data;
    
    @Autowired
    OfertaDataOnDemand TitulacionesDataOnDemand.ofertaDataOnDemand;
    
    public Titulaciones TitulacionesDataOnDemand.getNewTransientTitulaciones(int index) {
        Titulaciones obj = new Titulaciones();
        setNombre(obj, index);
        return obj;
    }
    
    public void TitulacionesDataOnDemand.setNombre(Titulaciones obj, int index) {
        String Nombre = "Nombre_" + index;
        obj.setNombre(Nombre);
    }
    
    public Titulaciones TitulacionesDataOnDemand.getSpecificTitulaciones(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Titulaciones obj = data.get(index);
        Long id = obj.getId();
        return Titulaciones.findTitulaciones(id);
    }
    
    public Titulaciones TitulacionesDataOnDemand.getRandomTitulaciones() {
        init();
        Titulaciones obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Titulaciones.findTitulaciones(id);
    }
    
    public boolean TitulacionesDataOnDemand.modifyTitulaciones(Titulaciones obj) {
        return false;
    }
    
    public void TitulacionesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Titulaciones.findTitulacionesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Titulaciones' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Titulaciones>();
        for (int i = 0; i < 10; i++) {
            Titulaciones obj = getNewTransientTitulaciones(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
