// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package iw2016_ett.domain;

import iw2016_ett.domain.Titulaciones;
import iw2016_ett.domain.TitulacionesDataOnDemand;
import iw2016_ett.domain.TitulacionesIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TitulacionesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TitulacionesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TitulacionesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TitulacionesIntegrationTest: @Transactional;
    
    @Autowired
    TitulacionesDataOnDemand TitulacionesIntegrationTest.dod;
    
    @Test
    public void TitulacionesIntegrationTest.testCountTitulacioneses() {
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", dod.getRandomTitulaciones());
        long count = Titulaciones.countTitulacioneses();
        Assert.assertTrue("Counter for 'Titulaciones' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TitulacionesIntegrationTest.testFindTitulaciones() {
        Titulaciones obj = dod.getRandomTitulaciones();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to provide an identifier", id);
        obj = Titulaciones.findTitulaciones(id);
        Assert.assertNotNull("Find method for 'Titulaciones' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Titulaciones' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TitulacionesIntegrationTest.testFindAllTitulacioneses() {
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", dod.getRandomTitulaciones());
        long count = Titulaciones.countTitulacioneses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Titulaciones', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Titulaciones> result = Titulaciones.findAllTitulacioneses();
        Assert.assertNotNull("Find all method for 'Titulaciones' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Titulaciones' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TitulacionesIntegrationTest.testFindTitulacionesEntries() {
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", dod.getRandomTitulaciones());
        long count = Titulaciones.countTitulacioneses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Titulaciones> result = Titulaciones.findTitulacionesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Titulaciones' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Titulaciones' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TitulacionesIntegrationTest.testFlush() {
        Titulaciones obj = dod.getRandomTitulaciones();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to provide an identifier", id);
        obj = Titulaciones.findTitulaciones(id);
        Assert.assertNotNull("Find method for 'Titulaciones' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTitulaciones(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Titulaciones' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TitulacionesIntegrationTest.testMergeUpdate() {
        Titulaciones obj = dod.getRandomTitulaciones();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to provide an identifier", id);
        obj = Titulaciones.findTitulaciones(id);
        boolean modified =  dod.modifyTitulaciones(obj);
        Integer currentVersion = obj.getVersion();
        Titulaciones merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Titulaciones' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TitulacionesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", dod.getRandomTitulaciones());
        Titulaciones obj = dod.getNewTransientTitulaciones(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Titulaciones' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Titulaciones' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TitulacionesIntegrationTest.testRemove() {
        Titulaciones obj = dod.getRandomTitulaciones();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulaciones' failed to provide an identifier", id);
        obj = Titulaciones.findTitulaciones(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Titulaciones' with identifier '" + id + "'", Titulaciones.findTitulaciones(id));
    }
    
}
